package twt.model;
// Generated 2018-5-31 11:25:56 by Hibernate Tools 3.5.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AnnouncementAdmin generated by hbm2java
 */
@Entity
@Table(name = "Announcement_Admin", catalog = "CommunitySystem")
public class AnnouncementAdmin implements java.io.Serializable {

	private AnnouncementAdminId id;

	public AnnouncementAdmin() {
	}

	public AnnouncementAdmin(AnnouncementAdminId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "name", column = @Column(name = "name", nullable = false)),
			@AttributeOverride(name = "time", column = @Column(name = "time", nullable = false, length = 19)),
			@AttributeOverride(name = "content", column = @Column(name = "content", nullable = false, length = 2048)) })
	public AnnouncementAdminId getId() {
		return this.id;
	}

	public void setId(AnnouncementAdminId id) {
		this.id = id;
	}

}
