package twt.model;
// Generated 2018-5-31 11:25:56 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Car generated by hbm2java
 */
@Entity
@Table(name = "Car", catalog = "CommunitySystem")
public class Car implements java.io.Serializable {

	private Integer id;
	private Household household;
	private String number;
	private CarPassRecord carPassRecord;

	public Car() {
	}

	public Car(Household household, String number) {
		this.household = household;
		this.number = number;
	}

	public Car(Household household, String number, CarPassRecord carPassRecord) {
		this.household = household;
		this.number = number;
		this.carPassRecord = carPassRecord;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "owner", nullable = false)
	public Household getHousehold() {
		return this.household;
	}

	public void setHousehold(Household household) {
		this.household = household;
	}

	@Column(name = "number", nullable = false, length = 7)
	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "car")
	public CarPassRecord getCarPassRecord() {
		return this.carPassRecord;
	}

	public void setCarPassRecord(CarPassRecord carPassRecord) {
		this.carPassRecord = carPassRecord;
	}

}
