package twt.model;
// Generated 2018-6-21 11:26:04 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Car generated by hbm2java
 */
@Entity
@Table(name = "Car", catalog = "CommunitySystem")
public class Car implements java.io.Serializable {

	private Integer id;
	private Household household;
	private String number;
	private Set<CarPassRecord> carPassRecordsForCarPassRecord = new HashSet<CarPassRecord>(0);
	private CarPassRecord carPassRecordById;

	public Car() {
	}

	public Car(Household household, String number) {
		this.household = household;
		this.number = number;
	}

	public Car(Household household, String number, Set<CarPassRecord> carPassRecordsForCarPassRecord,
			CarPassRecord carPassRecordById) {
		this.household = household;
		this.number = number;
		this.carPassRecordsForCarPassRecord = carPassRecordsForCarPassRecord;
		this.carPassRecordById = carPassRecordById;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "owner", nullable = false)
	public Household getHousehold() {
		return this.household;
	}

	public void setHousehold(Household household) {
		this.household = household;
	}

	@Column(name = "number", nullable = false, length = 7)
	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "carByCarPassRecord")
	public Set<CarPassRecord> getCarPassRecordsForCarPassRecord() {
		return this.carPassRecordsForCarPassRecord;
	}

	public void setCarPassRecordsForCarPassRecord(Set<CarPassRecord> carPassRecordsForCarPassRecord) {
		this.carPassRecordsForCarPassRecord = carPassRecordsForCarPassRecord;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "carById")
	public CarPassRecord getCarPassRecordById() {
		return this.carPassRecordById;
	}

	public void setCarPassRecordById(CarPassRecord carPassRecordById) {
		this.carPassRecordById = carPassRecordById;
	}

}
