package twt.model;
// Generated 2018-6-21 11:26:04 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * CarPassRecord generated by hbm2java
 */
@Entity
@Table(name = "CarPassRecord", catalog = "CommunitySystem")
public class CarPassRecord implements java.io.Serializable {

	private int id;
	private Car carByCarPassRecord;
	private Car carById;
	private Date time;
	private int door;

	public CarPassRecord() {
	}

	public CarPassRecord(Car carById, Date time, int door) {
		this.carById = carById;
		this.time = time;
		this.door = door;
	}

	public CarPassRecord(Car carByCarPassRecord, Car carById, Date time, int door) {
		this.carByCarPassRecord = carByCarPassRecord;
		this.carById = carById;
		this.time = time;
		this.door = door;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "carById"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "carPassRecord")
	public Car getCarByCarPassRecord() {
		return this.carByCarPassRecord;
	}

	public void setCarByCarPassRecord(Car carByCarPassRecord) {
		this.carByCarPassRecord = carByCarPassRecord;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Car getCarById() {
		return this.carById;
	}

	public void setCarById(Car carById) {
		this.carById = carById;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time", nullable = false, length = 19)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	@Column(name = "door", nullable = false)
	public int getDoor() {
		return this.door;
	}

	public void setDoor(int door) {
		this.door = door;
	}

}
