package twt.model;
// Generated 2018-5-31 11:25:56 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * CarPassRecord generated by hbm2java
 */
@Entity
@Table(name = "CarPassRecord", catalog = "CommunitySystem")
public class CarPassRecord implements java.io.Serializable {

	private int id;
	private Car car;
	private Date time;
	private int door;

	public CarPassRecord() {
	}

	public CarPassRecord(Car car, Date time, int door) {
		this.car = car;
		this.time = time;
		this.door = door;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "car"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Car getCar() {
		return this.car;
	}

	public void setCar(Car car) {
		this.car = car;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time", nullable = false, length = 19)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	@Column(name = "door", nullable = false)
	public int getDoor() {
		return this.door;
	}

	public void setDoor(int door) {
		this.door = door;
	}

}
