package twt.model;
// Generated 2018-5-24 10:57:55 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Express generated by hbm2java
 */
@Entity
@Table(name = "Express", catalog = "CommunitySystem")
public class Express implements java.io.Serializable {

	private Integer id;
	private Household household;
	private String number;
	private Date time;
	private int picked;

	public Express() {
	}

	public Express(Household household, String number, Date time, int picked) {
		this.household = household;
		this.number = number;
		this.time = time;
		this.picked = picked;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "phone", nullable = false)
	public Household getHousehold() {
		return this.household;
	}

	public void setHousehold(Household household) {
		this.household = household;
	}

	@Column(name = "number", nullable = false)
	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time", nullable = false, length = 19)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	@Column(name = "picked", nullable = false)
	public int getPicked() {
		return this.picked;
	}

	public void setPicked(int picked) {
		this.picked = picked;
	}

}
