package twt.model;
// Generated 2018-5-31 11:25:56 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Guard generated by hbm2java
 */
@Entity
@Table(name = "Guard", catalog = "CommunitySystem")
public class Guard implements java.io.Serializable {

	private Integer id;
	private String name;
	private String phone;
	private Integer sex;
	private Date birthday;
	private Date starttime;
	private Date stoptime;
	private int salary;

	public Guard() {
	}

	public Guard(String name, String phone, Date starttime, Date stoptime, int salary) {
		this.name = name;
		this.phone = phone;
		this.starttime = starttime;
		this.stoptime = stoptime;
		this.salary = salary;
	}

	public Guard(String name, String phone, Integer sex, Date birthday, Date starttime, Date stoptime, int salary) {
		this.name = name;
		this.phone = phone;
		this.sex = sex;
		this.birthday = birthday;
		this.starttime = starttime;
		this.stoptime = stoptime;
		this.salary = salary;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "phone", nullable = false, length = 11)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "sex")
	public Integer getSex() {
		return this.sex;
	}

	public void setSex(Integer sex) {
		this.sex = sex;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "birthday", length = 19)
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "starttime", nullable = false, length = 19)
	public Date getStarttime() {
		return this.starttime;
	}

	public void setStarttime(Date starttime) {
		this.starttime = starttime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "stoptime", nullable = false, length = 19)
	public Date getStoptime() {
		return this.stoptime;
	}

	public void setStoptime(Date stoptime) {
		this.stoptime = stoptime;
	}

	@Column(name = "salary", nullable = false)
	public int getSalary() {
		return this.salary;
	}

	public void setSalary(int salary) {
		this.salary = salary;
	}

}
