package twt.model;
// Generated 2018-6-21 11:26:04 by Hibernate Tools 3.5.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * LoginHousehold generated by hbm2java
 */
@Entity
@Table(name = "Login_Household", catalog = "CommunitySystem")
public class LoginHousehold implements java.io.Serializable {

	private LoginHouseholdId id;

	public LoginHousehold() {
	}

	public LoginHousehold(LoginHouseholdId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "name", column = @Column(name = "name", nullable = false)),
			@AttributeOverride(name = "phone", column = @Column(name = "phone", nullable = false, length = 11)),
			@AttributeOverride(name = "password", column = @Column(name = "password", nullable = false)) })
	public LoginHouseholdId getId() {
		return this.id;
	}

	public void setId(LoginHouseholdId id) {
		this.id = id;
	}

}
